require 'rubygems'
require 'hoe'

$:.unshift(File.dirname(__FILE__) + "/lib")
require 'funit'

Hoe.new('funit', Funit::VERSION) do |p|
  p.rubyforge_name = 'funit'
  p.author = 'Karen Bibb, Bil Kleb, Beth Lee-Rausch, Mike Park, Bill Wood'
  p.email = 'funit-support@rubyforge.org'
  p.summary = 'A Fortran 95 xUnit testing framework.'
  p.description = p.paragraphs_of('README.txt', 2..5).join("\n\n")
  p.url = p.paragraphs_of('README.txt', 0).first.split(/\n/)[1..-1]
  p.changes = p.paragraphs_of('History.txt', 0..1).join("\n\n")
  p.remote_rdoc_dir = '' # release webpages to Rubyforge root
  p.clean_globs = [ "**/*_fun.f90", "examples/**/TestRunner*", "**/*.o", "**/*.mod", "**/*.MOD" ]
end
