require 'rubygems'
Gem::manage_gems
require 'rake/gempackagetask'

spec = Gem::Specification.new do |s|

  s.name     = 'fUnit'
  s.version  = '2.0.0'
  s.author   = 'fUnit Team'
  s.email    = 'funit-support@rubyforge.org'
  s.homepage = 'http://funit.rubyforge.org/'

  s.rubyforge_project = 'funit'

  s.platform = Gem::Platform::RUBY

  s.summary  = 'A Fortran Unit Testing Framework'

  s.files = FileList["{bin,tests,lib,docs}/**/*"].exclude('rdoc').to_a

  s.require_path       = 'lib'
  s.autorequire        = 'funit'
  s.bindir             = 'bin'
  s.executables        = ['funit']
  s.test_file          = 'tests/ts_funit.rb'
  s.has_rdoc           = true
  s.extra_rdoc_files   = ["README", "LICENSE", "INSTALL"]

end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_tar = true
  pkg.need_zip = true
end
