# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/funit.rb'

Hoe.new('funit', Funit::VERSION) do |p|
  p.rubyforge_name = 'funit'
  p.author = 'Karen Bibb, Bil Kleb, Beth Lee-Rausch, Mike Park, Bill Wood'
  p.email = 'funit-support@rubyforge.org'
  p.summary = 'A Fortran 95 xUnit testing framework.'
  p.description = p.paragraphs_of('README.txt', 2..5).join("\n\n")
  p.url = p.paragraphs_of('README.txt', 0).first.split(/\n/)[1..-1]
  p.changes = p.paragraphs_of('History.txt', 0..1).join("\n\n")
  p.remote_rdoc_dir = '' # To release to Rubyforge root
end

# vim: syntax=Ruby
