# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/namelists.rb'

Hoe.new('namelists', Namelists::VERSION) do |namelists|
  namelists.developer('Bil Kleb', 'Bil.Kleb@nasa.gov')
end

# vim: syntax=Ruby
