#!/usr/bin/env ruby
#
# $Id$
#
# Generates a Fortran 90 code which runs all the mobility
# test suites in this directory (or only those test suites
# specified on the command line).

require 'FTKfunctions'
require 'TestSuite'

checkForCompiler

puts

writeTestRunner(testSuites = parseCommandLine)

# convert each *TS.ftk file into pure Fortran9x files:

testSuites.each do |testSuite|

 testSuiteF90 = TestSuite.new(testSuite)

 ftkFile = "#{testSuite}TS.ftk"
 $stderr.print "parsing #{ftkFile}.. "

 File.open(ftkFile) do |$stdin|
  testSuiteF90.puts $_ \
   until $stdin.gets =~ \
    /(begin|end)(Setup|Teardown|Test)|Is(RealEqual|Equal|False|True|EqualWithin)\(.*\)/
  testSuiteF90.puts " contains\n\n"

  loop do
   case $_
    when /^\s*!/
     testSuiteF90.puts $_
    when /beginSetup/
     testSuiteF90.addtoSetup
    when /beginTeardown/
     testSuiteF90.addtoTeardown
    when /beginTest\s+(\w+)/
     testSuiteF90.aTest($1,testSuite)
    when /beginTest/
     syntaxError "no name given for beginTest", testSuite
    when /end(Setup|Teardown|Test)/
     syntaxError "no matching begin#$1", testSuite
    when $assertRegEx
     syntaxError "#$1 assert not in a test block", testSuite
    else
     testSuiteF90.puts $_
   end
   break unless $stdin.gets
  end

 end

 $stderr.puts "complete."
 testSuiteF90.close

end

runTests testSuites
