#!/usr/bin/env ruby
#
# $Id$
#
# Generates a Fortran 90 code which runs all the mobility
# test suites in this directory (or only those test suites
# specified on the command line).

require 'checkForCompiler'
require 'checkCommandLine'
require 'writeTestRunner'
require 'TestSuite'
require 'runTests'

checkForCompiler

testSuites = Dir["*TS.ftk"]
testSuites.each { |suiteName| suiteName.chomp! "TS.ftk" }
testSuites = checkCommandLineFor testSuites

writeTestRunner testSuites

# convert each *TS.ftk file into pure Fortran9x files:

testSuites.each do |testSuite|

 testSuiteF90 = TestSuite.new(testSuite)

 File.open(testSuite+"TS.ftk") do |$stdin|

  testSuiteF90.puts $_ until gets=~/begin(Setup|Teardown|Test)/
  testSuiteF90.puts " contains\n\n"

  loop do
   case $_
    when /beginSetup/
     testSuiteF90.addtoSetup
    when /beginTeardown/
     testSuiteF90.addtoTeardown
    when /beginTest \s*(.*)/
     testSuiteF90.aTest($1)
    when /beginTest/
     $stderr.print "No test name following beginTest: " \
                   "Line #{lineNumber} of #{testSuite}TS.ftk\n"
     exit 1
    when /Is(RealEqual|Equal|False|True|EqualWithin)/
     $stderr.print "Error: assertion outside of a test block: " \
                   "Line #{lineNumber} of #{testSuite}TS.ftk\n"
     exit 1
    else
     puts $_
   end
   break unless gets
  end

 end

 testSuiteF90.close

end

runTests testSuites
