#!/usr/bin/env ruby
#
# $Id$
#
# Generates a Fortran 90 code which runs all the mobility
# test suites in this directory (or only those test suites
# specified on the command line).

require 'FTKfunctions'
require 'TestSuite'

checkForCompiler
writeTestRunner(testSuites = parseCommandLine)

# convert each *TS.ftk file into pure Fortran9x files:

testSuites.each do |testSuite|

 testSuiteF90 = TestSuite.new(testSuite)

 File.open("#{testSuite}TS.ftk") do |$stdin|
  testSuiteF90.puts $_ until $stdin.gets=~/begin(Setup|Teardown|Test)/
  testSuiteF90.puts " contains\n\n"

  loop do
   case $_
    when /beginSetup/
     testSuiteF90.addtoSetup
    when /beginTeardown/
     testSuiteF90.addtoTeardown
    when /beginTest \s*(.*)/
     testSuiteF90.aTest($1,testSuite)
    when /beginTest/
     syntaxError "No test name following beginTest:"
    when /Is(RealEqual|Equal|False|True|EqualWithin)/
     syntaxError "Error: assertion outside of a test block:"
    else
     puts $_
   end
   break unless $stdin.gets
  end

 end

 testSuiteF90.close

end

runTests testSuites
