! TestRunner.f90 - runs Fortran mobility test suites
!
! [Dynamically generated by FTKtest Ruby script Wed Nov 07 07:53:00 EST 2001.]

program TestRunner

 use GasModelTS
 use FluxFunctionsTS

 implicit none

 integer :: numTests, numAsserts, numAssertsTested, numFailures

 print *, ""
 print *, "GasModel test suite:"
 call TSGasModel( numTests, numAsserts, numAssertsTested, numFailures )
 print *, "Completed", numTests-numFailures, "of", numTests, &
  "tests comprising", numAssertsTested, "of", numAsserts, "possible asserts."

 print *, ""
 print *, "FluxFunctions test suite:"
 call TSFluxFunctions( numTests, numAsserts, numAssertsTested, numFailures )
 print *, "Completed", numTests-numFailures, "of", numTests, &
  "tests comprising", numAssertsTested, "of", numAsserts, "possible asserts."

 print *, ""

end program TestRunner
