require 'rubygems'
require 'hoe'

$:.unshift File.join( File.dirname(__FILE__), 'lib' )
require 'uq4sim'

Hoe.new('uq4sim', Uq4sim::VERSION) do |p|
  p.rubyforge_name = 'nasarb'
  p.author = 'Bil Kleb'
  p.email = 'Bil.Kleb@NASA.gov'
  p.summary = 'Uncertainty quantification for modeling and simulation codes.'
  p.description = p.paragraphs_of('README.txt', 3..4).join("\n\n")
  p.url = p.paragraphs_of('README.txt', 1).first.gsub(/^\* /, '').split(/\n/)
  p.changes = p.paragraphs_of('History.txt', 0..1).join("\n\n")
end