# -*- ruby -*-

require 'rubygems'
require 'hoe'

$:.push 'lib'
require 'uq4sim'

Hoe.new('uq4sim', Uq4sim::VERSION) do |p|
  p.rubyforge_name = 'nasarb'
  p.remote_rdoc_dir = 'uq4sim' 
  p.author = 'Bil Kleb'
  p.email = 'Bil.Kleb@NASA.gov'
  p.summary = p.paragraphs_of('README.txt', 3).to_s
  p.description = p.paragraphs_of('README.txt', 4..5).join("\n\n")
  p.url = p.paragraphs_of('README.txt', 1).first.gsub(/^\* /, '').split(/\n/)
  p.changes = p.paragraphs_of('History.txt', 0..1).join("\n\n")
  p.rsync_args = '-rpv --delete' # to preserve group permissions
end

# vim: syntax=Ruby
