# Rakefile for fUnit  -*- ruby -*-
#
# Copyright 2006 United States Government as represented by NASA Langley
# Research Center, Hampton, Virginia.
#
# This file is governed by the OSI-approved, NASA Open Source Agreement.
# See COPYING for details.

begin
  require 'rubygems'
  require 'rake/gempackagetask'
  require 'code_statistics'
rescue Exception
  nil
end

require 'rake/testtask'
require 'rake/rdoctask'

PKG_VERSION = '0.0.2'

PKG_FILES = FileList[
  '[A-Z]*',
  'bin/**/*',
  'docs/**/*',
  'examples/**/*',
  'lib/**/*',
  'tests/**/*.rb'
]

desc 'Default task'
task :default => [:test]

rd = Rake::RDocTask.new do |rdoc|
  rdoc.main = 'README'
  rdoc.rdoc_dir = 'docs/html'
  rdoc.title = 'fUnit: Fortran Unit Testing'
  rdoc.options << '--inline-source' << '--main' << 'README'
  rdoc.rdoc_files.include( 'README', 'COPYING' )
  rdoc.rdoc_files.include( 'lib/**/*.rb' )
end

desc 'Upload current documentation to Rubyforge'
task :upload_docs => [:rdoc] do
  sh 'scp -r docs/html/* rubyforge.org:/var/www/gforge-projects/funit/'
end

Rake::TestTask.new do |t|
  t.test_files = [ 'tests/ts_funit.rb' ]
  t.warning = true
  t.verbose = true
  t.libs << 'tests'
end

if ! defined?(Gem)
  $stderr.puts 'Package Target requires RubyGEMs'
else
  spec = Gem::Specification.new do |s|
    s.name     = 'fUnit'
    s.version  = PKG_VERSION
    s.files    = PKG_FILES.to_a
    s.author   = 'fUnit Team'
    s.email    = 'funit-support@rubyforge.org'
    s.homepage = 'http://funit.rubyforge.org/'
    s.platform = Gem::Platform::RUBY
    s.summary  = 'A Fortran Unit Testing Framework'
    s.description = <<-EOF
      FUnit is a unit testing framework for Fortran modules.
      Unit tests are written in Fortran fragments that use a small
      set of testing-specific extensions.  FUnit transforms these
      fragments into valid Fortran code and compiles, links, and
      runs them against the module under test.
    EOF
    s.rubyforge_project  = 'funit'
    s.require_path       = 'lib'
    s.autorequire        = 'funit'
    s.bindir             = 'bin'
    s.executable         = 'funit'
    s.test_suite_file    = 'tests/ts_funit.rb'
    s.has_rdoc           = true
    s.rdoc_options       = rd.options
    s.extra_rdoc_files   = rd.rdoc_files.reject{|f| f.match(/\.rb$/)}.to_a
  end
  Rake::GemPackageTask.new(spec) do |pkg|
    pkg.need_tar = true
    pkg.need_zip = true
  end
end

desc 'Show code statistics'
task :stats do
  if ! defined?(CodeStatistics)
    $stderr.puts 'Stats target requires Rails'
  else
    CodeStatistics.new( %w[Source lib], %w[Units tests] ).to_s
  end
end
