# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/watch-paths.rb'

Hoe.new( 'watch-paths', WatchPaths::VERSION ) do |p|
  p.rubyforge_name = 'nasarb'
  p.author = 'Bil Kleb'
  p.email = 'Bil.Kleb@nasa.gov'
  p.summary = p.paragraphs_of('README.txt', 3).to_s
  p.description = p.paragraphs_of('README.txt', 3).to_s
  p.url = p.paragraphs_of('README.txt', 1).to_s.split(/\n/)[1..-1]
  p.changes = p.paragraphs_of('History.txt', 0..1).join("\n\n")
  p.rsync_args = '-rpv --delete' # to preserve group permissions
end

# vim: syntax=Ruby
