# -*- ruby -*-

require 'rubygems'
require 'hoe'

require './lib/fortran'

Hoe.new( 'fortran', Fortran::VERSION ) do |p|
  p.rubyforge_name = 'nasarb'
  p.author      = %w( 'Bil Kleb', 'Mike Park', 'Bill Wood' )
  p.email       = 'Bil.Kleb@NASA.gov'
  p.url         = p.paragraphs_of( 'README.txt', 1 ).to_s.gsub(/^\* /, '').split(/\n/)
  p.summary     = p.paragraphs_of( 'README.txt', 3 ).to_s
  p.description = p.paragraphs_of( 'README.txt',  3..4 ).join("\n\n")
  p.changes     = p.paragraphs_of( 'History.txt', 0..1 ).join("\n\n")
  p.remote_rdoc_dir = 'fortran' # release webpages to http://nasarb.rubyforge.org/fortran
  p.rsync_args << ' --exclude=statsvn/'
end

# vim: syntax=Ruby
