# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/namelists.rb'

Hoe.new('namelists', Namelists::VERSION) do |p|
  # p.rubyforge_name = 'namelistsx' # if different than lowercase project name
  # p.developer('FIX', 'FIX@example.com')
end

# vim: syntax=Ruby
