# -*- ruby -*-

require 'hoe'

Hoe.spec 'fortran' do |p|
  p.group_name  = 'nasarb'
  p.remote_rdoc_dir = 'fortran'
  p.author      = ['Bil Kleb', 'Mike Park', 'Bill Wood']
  p.email       = 'Bil.Kleb@NASA.gov'
  p.licenses    = ['NASA-1.3']
end

# vim: syntax=Ruby
