# -*- ruby -*-

require 'rubygems'
require 'hoe'

$:.unshift File.join( File.dirname(__FILE__), 'lib' )
require 'funit'

Hoe.new('funit', Funit::VERSION) do |p|
  p.rubyforge_name = 'nasarb'
  p.extra_deps << [ 'fortran', '>= 1.0.0' ]
  p.author = ['Karen Bibb','Bil Kleb','Beth Lee-Rausch','Mike Park','Bill Wood']
  p.email = 'funit-support@rubyforge.org'
  p.summary = 'A Fortran unit testing framework.'
  p.description = p.paragraphs_of('README.txt', 2..3).join("\n\n")
  p.url = p.paragraphs_of('README.txt', 1).first.gsub(/^\* /, '').split(/\n/)
  p.changes = p.paragraphs_of('History.txt', 0..1).join("\n\n")
  p.remote_rdoc_dir = 'funit' # release webpages to root (otherwise dropped in rubyforge_name subdir)
  p.clean_globs.concat %w( **/*_fun.f90 examples/**/TestRunner* **/*.o **/*.mod **/*.MOD )
  p.rsync_args << ' --exclude=statsvn/'
end
